version: '3.9'
services:
  boombot:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: 2333

  lavalink:
    image: fredboat/lavalink:dev
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml



    
